name: benchmark
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - matplotlib
  - pyqt
  - ome-zarr
  - zarr=2.15*
  - pip:
      - pytest
      - cmake
      - ml-dtypes
      - tensorstore
