name: benchmark
channels:
  - defaults
  - conda-forge
  - rapidsai
dependencies:
  - pip
  - matplotlib
  - napari
  - pyqt
  - ome-zarr
  - kvikio
  - zarr=2.15*
  - pip:
      - ml-dtypes
      - tensorstore
